# Generated by Django 2.2.2 on 2019-12-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCompareHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=255)),
                ('product_name', models.TextField(max_length=255)),
                ('cover', models.IntegerField(default=0)),
                ('features', models.IntegerField(default=0)),
                ('premium', models.IntegerField(default=0)),
            ],
        ),
    ]
