# Generated by Django 2.2.2 on 2019-12-31 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=255)),
                ('name_user', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('sex', models.BooleanField()),
                ('city', models.CharField(max_length=255)),
                ('birth_day', models.DateField(auto_now=True)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('occupation', models.CharField(max_length=255)),
                ('id_products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.ProductCompareHealth')),
            ],
        ),
        migrations.CreateModel(
            name='ChildPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('name_user', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('birth_day', models.DateField(auto_now=True)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('relationship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.CustomerParent')),
            ],
        ),
    ]
